source = ~/.config/hypr/theme.conf

background = $crust
base = $base
text = $text
alternate_base = $mantle
bright_text = $subtext1
accent = $rosewater
accent_secondary = $mauve
font_family = "Inter"
font_family_monospace = "JetBrains Mono Nerd Font"
