windowrule {
    name = nm-connection-editor
    match:class = nm-connection-editor

    float = yes
    center = yes

    size = 500 500
}

windowrule {
    name = blueman-manager
    match:class = blueman-manager

    float = yes
    center = yes

    size = 500 500
}

windowrule {
    name = bottom
    match:class = com.mitchellh.ghostty
    match:title = Bottom

    float = yes
    center = yes

    size = 1280 720
}

windowrule {
    name = bitwarden=popup
    match:title = Bitwarden

    float = yes
    center = yes

    size = 400 800
}

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
