---
name: Build NixOS
on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  seamoth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v15
        with:
          name: evictedcucumber
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build Seamoth
        run: |
          nix build .#nixosConfigurations.seamoth.config.system.build.toplevel \
            --no-link \
            --print-build-logs
  snowfox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v15
        with:
          name: evictedcucumber
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build Snowfox
        run: |
          nix build .#nixosConfigurations.snowfox.config.system.build.toplevel \
            --no-link \
            --print-build-logs
  tadpole:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v15
        with:
          name: evictedcucumber
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build Tadpole
        run: |-
          nix build .#nixosConfigurations.tadpole.config.system.build.toplevel \
            --no-link \
            --print-build-logs
